# Generated by Django 6.0.2 on 2026-03-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phonenumber',
            field=models.CharField(max_length=10),
        ),
    ]
