# Generated by Django 6.0.2 on 2026-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_myappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='areaofspecialisation',
            field=models.CharField(max_length=20),
        ),
    ]
